### ISSUE TITLE
debug logs

### ISSUE THREAD

**Issue by feferka** [qaware/collection-cacheable-for-spring#11]
By adding dependency _collection-cacheable-for-spring-starter_ into my Spring Boot app it stops logging Spring cache debug logs. Log were enabled by adding  

logging:
  level:
    org.springframework.cache: TRACE

into application.yaml. With CollectionCacheable cache debug logs are malfunctioning.

**Comment by neiser** [comment]
Hi @feferka,
I've added some trace logs similar to the ones for "normal" caching operation. Let me know if that suits you, if not, please feel free to open a PR adding/modifying trace log statements. See 74e8d3742d1240a0eb3de422b970916d4a257048 for an example.
