### ISSUE TITLE
I think you can provide Hash-based Cache storage

### ISSUE THREAD

**Issue by YAGAMIL** [qaware/collection-cacheable-for-spring#6]
Thank you for providing this extension, which helps me solve a lot of problems.
If I use Redis, in fact using Redis to make a cache is a very common operation, but I don't want all the default String, but use Hash storage, which is more in line with the scene, I think it can be used as an open to developer selection

**Comment by neiser** [comment]
@YAGAMIL Can you please elaborate? What exactly do you want to be changed? Do you have an issue at all?

This library doesn't say anything of the cache backend. That's abstracted by Spring already and this library builds upon it.

**Comment by YAGAMIL** [comment]
> @YAGAMIL Can you please elaborate? What exactly do you want to be changed? Do you have an issue at all?
> 
> This library doesn't say anything of the cache backend. That's abstracted by Spring already and this library builds upon it.
I mean, you can rewrive the Rediscachemanager separately to provide special use of Redis storage, but I should need to write it yourself.
我的意思是，可以单独重写RedisCacheManager来提供对Redis存储的特别，不过这个我应该需要自行编写了

**Comment by neiser** [comment]
I don't speak Chinese but I suppose we can close that issue too.
